version: '3'

services:
  printer:
    build:
      context: ./.docker/local
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - "8008:8008"
    command: "npm run start-local"
    restart: always